apiVersion: v1
kind: Service
metadata:
  name: frig-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: frig
    chart: {{ template "forgerock.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  selector:
    app: frig
  ports:
    - name: tcp-http
      port: 80
      targetPort: 8080
{{- if .Values.isStatefulSet }}
---
apiVersion: v1
kind: Service
metadata:
  name: frig
  namespace: {{ .Release.Namespace }}
  labels:
    app: frig
spec:
  clusterIP: None
  selector:
    app: frig
  ports:
    - name: tcp-http
      port: 8080
{{- end }}